[alias]
b = "build"
br = "build --release"
r = "run"
rr = "run --release"
c = "check"
t = "test"

[term]
color = 'auto'

[source.crates-io]
replace-with = 'bfsu'

[source.bfsu]
registry = "sparse+https://mirrors.bfsu.edu.cn/crates.io-index/"

[registries.bfsu]
index = "sparse+https://mirrors.bfsu.edu.cn/crates.io-index/"

[net]
git-fetch-with-cli = true

